### ISSUE TITLE
get_post problem

### ISSUE THREAD

**Issue by fxnormaluser** [xeroc/piston-lib#37]
My scripts keep crashing ( sporadically ) like this:

```
File "/home/felixxx/.local/lib/python3.5/site-packages/piston_lib-0.5.2-py3.5.egg/piston/steem.py", line 935, in get_post
File "/home/felixxx/.local/lib/python3.5/site-packages/piston_lib-0.5.2-py3.5.egg/piston/post.py", line 47, in __init__
File "/home/felixxx/.local/lib/python3.5/site-packages/piston_lib-0.5.2-py3.5.egg/piston/post.py", line 71, in refresh
piston.exceptions.PostDoesNotExist: Post does not exist: @steemit-health/enter-your-daily-health-score-for-sunday-april-16-a-healthy-steem-distribution-activity
```

**But the post exists.** 
Issue appears with different nodes.

**Comment by bycz6** [comment]
Hello,

Same problem

```
New post by @bycz https://steemit.com/teste/@bycz/teste-v4
====> Upvoted

Traceback (most recent call last):
  File "votebot.py", line 88, in <module>
    feed()

  File "votebot.py", line 40, in feed
    if comment.author in my_subscriptions:
  File "/home/bycz/.local/lib/python3.5/site-packages/piston_lib-0.5.4-py3.5.egg/piston/post.py", line 138, in __getattr__

  File "/home/bycz/.local/lib/python3.5/site-packages/piston_lib-0.5.4-py3.5.egg/piston/post.py", line 71, in refresh

piston.exceptions.PostDoesNotExist: Post does not exist: @acidyo/re-acidyo-re-mindhunter-mindhunter-15k-post-senior-steemit-poster-photographer-philosopher-steemophile-sapiophile-lynchian-quirky-global-digital-nomad-20170415t000250212z
```

**Comment by Netherdrake** [comment]
It doesn't exist on steemit either:
https://steemit.com/@acidyo/re-acidyo-re-mindhunter-mindhunter-15k-post-senior-steemit-poster-photographer-philosopher-steemophile-sapiophile-lynchian-quirky-global-digital-nomad-20170415t000250212z

**Comment by fxnormaluser** [comment]
It got deleted.

I'm not sure, if it still existed when I tried loading it.

The issue happened with other posts too, that clearly were not deleted.
I will wait for another case to happen.

**Comment by Netherdrake** [comment]
It is not a `piston-lib` issue.

My speculation is that one of the steemd nodes in the cluster went (temporarily?) out of sync.

**Comment by bycz6** [comment]
How can I keep my script running when this error occurs?

**Comment by srlmitch** [comment]
Also getting this issue on multiple scripts...

Can anyone show a solution of how to avoid/bypass postdoesnotexist?

**Comment by Netherdrake** [comment]
If the `PostDoesNotExist` error is erronious, switch to a steemd node that actually works.

You can change the node globally via:
```piston set node```
