### ISSUE TITLE
Transfer not authorized

### ISSUE THREAD

**Issue by atthom** [xeroc/piston-lib#58]
Hello,
I have trouble to transfer funds with piston-cli

```python
steem = Steem(wif=posting, node="wss://this.piston.rocks")
steem.transfer(to="someone-else", amount=55, asset="SBD", memo=memo, account=steemit_account)
```
It gave me this error:
```python
Traceback (most recent call last):
  	File "C:\_Installs\Anaconda\lib\site-packages\pistonapi\steemnoderpc.py", line 124, in rpcexec
	return super(SteemNodeRPC, self).rpcexec(payload)
  	File "C:\_Installs\Anaconda\lib\site-packages\grapheneapi\graphenewsrpc.py", line 160, in rpcexec
    raise RPCError(ret['error']['message'])
    grapheneapi.graphenewsrpc.RPCError: 3010000 tx_missing_active_auth: missing required active authority
    Missing Active Authority [myaccount]
    [...]
```

I suppose the Steem instance doesn't have the active key to transfer funds.
I didn't found any example or test that could help me to do it.

**Comment by ArtGenesis** [comment]
yes , you need active key to transfer, try like this
steem = Steem( keys = { 'active': 'your active wif key' }, node="wss://this.piston.rocks")

**Comment by atthom** [comment]
thanks a lot !
