### ISSUE TITLE
Heroku python3.6 piston import error

### ISSUE THREAD

**Issue by ghost** [xeroc/piston-lib#69]
It appears that the heroku python3.6 site package for piston is incomplete or, more likely, I am doing something wrong.  I'm trying to run Charlesjlee's steembot that is built on piston.  It looks like it is untouched on github for around a year, so this seemed the best place for me to beg for help.  It builds on heroku but when I run it, I get:

heroku run python bot.py -a epfsteembot01
Running python bot.py on epfsteembot01... up, run.8416 (Free)
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from piston.steem import Steem
  File "/app/.heroku/python/lib/python3.6/site-packages/piston/steem.py", line 3, in <module>
    from steem.steem import SteemConnector as SteemConnectorSteem
ImportError: cannot import name 'SteemConnector'

**Comment by ghost** [comment]
had to be from piston import Steem
